take .zst rootfs compression into account
Signed-off-by: Kaiwan N Billimoria <kaiwan.billimoria@gmail.com>

diff --git a/mnt_rootfs b/mnt_rootfs
--- a/mnt_rootfs
+++ b/mnt_rootfs
@@ -2,6 +2,9 @@
 # Part of the 'yocto_tools' GitHub repo
 # 'A small, simple and useful tool collection for Yocto'
 #  https://github.com/kaiwan/yocto_tools
+#
+# Mounts the latest rootfs ext[34] image found; if none present, aborts..
+# Takes .zst compression into account...
 # (c) Kaiwan NB, kaiwanTECH
 # License: MIT
 export name=$(basename "$0")
@@ -18,17 +21,25 @@ source "${PFX}"/common || {
 setup_env #-q
 
 # FIXME: select a given rootfs based on a image basename (as there can be several)
-EXT_IMG=$(ls -1t ${TMPD}/deploy/images/${MACHINE}/${IB}-${MACHINE}.*ext[34] |head -n1 || die "couldn't fetch any ext[34] format image file")
+EXT_IMG=$(ls -1t ${TMPD}/deploy/images/${MACHINE}/${IB}-${MACHINE}.*ext[34]* |head -n1 || die "couldn't fetch any ext[34] format image file")
 #echo "EXT_IMG = $EXT_IMG"
 EXT_IMG=$(realpath ${EXT_IMG})
+FINALE_IMG=${EXT_IMG}
+file ${EXT_IMG} |grep "Zstandard compressed data" >/dev/null && {
+  echo "The rootfs is a ZST Zstandard compressed file, extracting now..."
+  zstd -d ${EXT_IMG} || die "couldn't extract"
+  FINAL_IMG=$(ls -1t ${TMPD}/deploy/images/${MACHINE}/${IB}-${MACHINE}.*ext[34])
+  ls -l ${FINAL_IMG}
+}
+
 echo "Loop mounting this file
-${EXT_IMG}
+${FINAL_IMG}
 as the rootfs, on mount point ${MOUNT_POINT} ...
 "
 
 sudo mkdir -p ${MOUNT_POINT} 2>/dev/null
 sudo umount ${MOUNT_POINT}/ 2>/dev/null || true
-sudo mount -o loop ${EXT_IMG} ${MOUNT_POINT}/ || die "loop mount failed" && true
+sudo mount -o loop ${FINAL_IMG} ${MOUNT_POINT}/ || die "loop mount failed" && true
 df -h |grep "${MOUNT_POINT}"
-echo "Mounted; *** DON'T forget to umount it when done !!! ***"
+echo "Successfully mounted; *** DON'T forget to umount it when done !!! ***"
 exit 0
