rm show some bb vars func; have an alt approach to disp bb vars if first one fails

diff --git a/showvars b/showvars
--- a/showvars
+++ b/showvars
@@ -7,68 +7,59 @@ source "${PFX}"/common || {
 }
 setup_env -q
 
-show_some_bb_vars()
+disp_bbvars()
 {
-# All vars (?) : https://docs.yoctoproject.org/current/genindex.html
-# is case-sensitive
-
-echo "--- Some bitbake variables ---"
-VARS2GET="\
-		ARCH CROSS_COMPILE \
-		BBFILES BUILDDIR \
-		CC CFLAGS CONFFILES CORE_IMAGE_EXTRA_INSTALL \
-		DISTRO DISTRO_NAME DISTROOVERRIDES \
-		EXTRA_IMAGE_FEATURES EXTRA_OEMAKE EXTRA_USERS_PARAMS \
-		FILES \
-		IMAGE_BASENAME IMAGE_FEATURES IMAGE_FSTYPES IMAGE_ROOTFS IMAGE_ROOTFS_EXTRA_SPACE \
-		 IMAGE_ROOTFS_SIZE INHIBIT_PACKAGE_DEBUG_SPLIT INHIBIT_PACKAGE_STRIP INITRAMFS_IMAGE \
-		 INITSCRIPT_NAME \
-		KERNEL_FEATURES KERNEL_VERSION KARCH KBRANCH KBUILD_DEFCONFIG \
-		WORKDIR \
-		"
-	#TODO- more to fill in
-
-for VAR in ${VARS2GET}
-do
-	echo -n "${VAR}: "
-	bitbake-getvar ${VAR} 2>/dev/null | tail -n1
-	echo
-done
+local RUN_DO_FILE=$(realpath ${1})
+[[ -z "${RUN_DO_FILE}" || ! -f ${RUN_DO_FILE} ]] && {
+	echo "couldn't get a WORKDIR/temp/run.do_<foo> file"
+	[[ ${TRY} -eq 2 ]] && exit 1 || return 1
+}
+echo "WORKDIR           = ${WORKDIR}
+run.do_<foo> file = ${RUN_DO_FILE}
+---------------------------------------------------------------------------------"
+echo "For recipe \"$1\", checking within it's run.do_<foo> file for bitbake variables therein
+---------------------------------------------------------------------------------"
+grep "^export" ${RUN_DO_FILE} |cut -d' ' -f2-
+[[ $? -ne 0 ]] && {
+	echo "No bitbake variables present here?"
+	[[ ${TRY} -eq 2 ]] && exit 1 || return 1
+}
+return 0
 }
 
 
 #--- 'main'
-
 [ $# -ne 1 ] && {
-	echo "Usage: ${name} recipe-name  (without the meta- prefix)
+	echo "Usage: ${name} recipe-name
 Tip: use
 	bitbake-layers show-recipes
 	bitbake-layers show-appends
-to get recipe names"
+to get recipe names.
+
+F.e.
+build_qemuarm64 $ bitbake-layers show-recipes | grep -B1 autotools-helloworld
+bbexample:                      ### <--- the recipe name here's 'bbexample'  ###
+  meta-autotools-helloworld 1.0
+"
 	exit 1
 }
-
-show_some_bb_vars
-echo "--------------------------------------------------------
-"
-
 RECIPE="$1"
 
-echo "bitbake -c listtasks ${RECIPE}"
-bitbake -c listtasks ${RECIPE} #2>/dev/null
-[[ $? -ne 0 ]] && failit "couldn't list tasks for recipe"
+WORKDIR=$(bitbake -e ${RECIPE} 2>/dev/null |grep -w "^WORKDIR" | awk -F'=' '{print $2}' |cut -d"\"" -f2) || true
+[ -z "${WORKDIR}" ] && failit "Couldn't get WORKDIR for recipe \"${RECIPE}\""
 
-echo "
-----------------------------------------------------------------------
-For recipe $1: WORKDIR/temp/run.do_compile : showing varaibles therein
-----------------------------------------------------------------------
+# Find a run.do_<foo> file under WORKDIR/temp
+TRY=1
+RUN_DO_FILE=$(ls -1 ${WORKDIR}/temp/run.do_* |head -n1) || true
+set +e
+disp_bbvars ${RUN_DO_FILE}
+[[ $? -ne 0 ]] && {
+	echo "
+>>> Retrying via other approach...
+^^^ !NOTE! the run.do_<foo> file can be any available one with the required info (not just this recipe's) ^^^
 "
-W1=$(bitbake -e ${RECIPE} 2>/dev/null |grep -w "^WORKDIR" | awk -F'=' '{print $2}' |cut -d"\"" -f2)
-[ -z "${W1}" ] && failit "Couldn't get WORKDIR for recipe \"${RECIPE}\""
-
-#cat ${WORKDIR}/temp/run.do_compile
-# See all vars for this recipe
-echo "--------------------------------------------------------
-"
-[ -f ${W1}/temp/run.do_listtasks ] && grep "^export" ${W1}/temp/run.do_listtasks |cut -d' ' -f2-
-
+	TRY=2
+	NEW_RUN_DO_FILE=$(find ${WORKDIR} -type f 2>/dev/null |xargs grep -H "^export" 2>/dev/null |head -n1 |cut -d: -f1)
+	disp_bbvars ${NEW_RUN_DO_FILE}
+}
+exit 0
