port for newer yocto >= 5.3 + cleanup the script
Signed-off-by: Kaiwan N Billimoria <kaiwan.billimoria@gmail.com>

diff --git a/yct_recipe_gen b/yct_recipe_gen
--- a/yct_recipe_gen
+++ b/yct_recipe_gen
@@ -7,6 +7,7 @@
 
 # yct_recipe_gen
 # A very simple Yocto recipe generator script.
+# Usage: yct_recipe_gen [-d] meta-<layername> recipe-name
 # (c) Kaiwan N Billimoria, kaiwanTECH
 #
 #----------------------------------------------------------------------
@@ -44,8 +45,10 @@ local RCP_FILES RCPF_ARR re
 while true ; do
   RCP_FILES=$(yad --file-selection --multiple  \
        --center --width=${wd} --height=${ht} \
-       --title="${name}: Select required files for 'files' dir (for ${LAYER}:${RCP_NAME})" 2>/dev/null)
-  [ ! -z "${RCP_FILES}" ] && {
+       --title="${name}: Select required files for 'files' dir (for ${LAYER}:${RCP_NAME})" 2>/dev/null || true)
+ dprint "RCP_FILES = ${RCP_FILES}"
+
+ if [[ ! -z "${RCP_FILES}" ]] ; then
     #echo "Required files : ${RCP_FILES}"
     IFS='|'  # delimiter that yad inserts
     read -ra RCPF_ARR <<< "${RCP_FILES}"
@@ -56,7 +59,10 @@ while true ; do
       cp --preserve=all "${RFIL}" "${RCP_FILES_DIR}"/
     done
     unset IFS
-  }
+  else
+    echo "Cancelled..." ; return
+  fi
+
   echo -n "Add more files to recipe's 'files' dir? [y/N] "
   read -r re
   #echo "re = ${re}"
@@ -76,12 +82,13 @@ echo
 echo "[+] Generate the layer's recipe file"
 
 local PV=0 PR=1
-local recipe_file=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}_${PV}.${PR}.bb
+#local recipe_file=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}_${PV}.${PR}.bb
+local recipe_file=${LAYER}/recipes-${layer_token2}/${RCP_NAME}/${RCP_NAME}_${PV}.${PR}.bb
 
 # TODO : TEMP
 #rm -f ${recipe_file}
 
-[ -f "${recipe_file}" ] && {
+[[ -f "${recipe_file}" ]] && {
   QP
   echo "
 *WARNING* skipping as recipe file already exists:
@@ -116,10 +123,13 @@ rm -f "${tmpf}"
 
 local D=""
 cat << @EOF@ > "${recipe_file}"
-# Recipe generated by ${name}
+# This recipe template's generated by the ${name} script, part of the simple
+# 'yocto-tools' repo:
+#  https://github.com/kaiwan/yocto_tools
 # (c) kaiwanTECH
 # $(date)
-# (Note- this script generates syntax appropriate for honister 3.4 onwards, the syntax is of the form x:y not x_y !
+# (Note- this script generates syntax appropriate for honister 3.4 onwards, the
+# syntax is of the form x:y not x_y !
 # For lower versions, you'll have to manually change the syntax.)
 DESCRIPTION = ""
 
@@ -159,6 +169,8 @@ SRC_URI = "${SRCURI_FILES}
 
 IMAGE_FEATURES += ""
 
+# NOTE !!!
+# From Yocto 5.3, pl change the variable WORKDIR to UNPACKDIR
 S = "\${WORKDIR}"
 # FYI, \${S} = \${WORKDIR} = \${TMPDIR}/work/\${PACKAGE_ARCH}-\${DISTRO}-\${TARGET_OS}/\${PN}/\${PV}-\${PR}
 #  \${D} = \${WORKDIR}/image
@@ -200,25 +212,37 @@ which yad >/dev/null || {
  sudo apt install yad )"
   exit 1
 }
-setup_env #-q  # from the 'common' script
-# By now, BUILDDIR is confirmed as okay; so lets proceed...
-[[ 0 -eq 1 ]] && {
-BUILDDIR=$(${PFX}/showvars2 |grep "^BUILDDIR" |awk -F'=' '{print $2}')
-[[ -z "${BUILDDIR}" ]] && die "couldn't fetch value of BUILDDIR"
-IMAGE_BASENAME=$(${PFX}/showvars2 |grep "^IMAGE_BASENAME" |cut -d: -f2)
-[[ -z "${IMAGE_BASENAME}" ]] && die "couldn't fetch value of IMAGE_BASENAME"
-MACHINE=$(${PFX}/showvars2 MACHINE |grep "^MACHINE" |cut -d: -f2|tail -n1)
-[[ -z "${MACHINE}" ]] && die "couldn't fetch value of MACHINE"
-}
 
-export BUILDDIR
+setup_env -q  # from the 'common' script
+
+set +u
+[ -z "${BUILDDIR}" ] && {
+  echo "${name}: we expect you to be running this script from within your Yocto workspace.
+So, you need to do that - source the Yocto environment first; typically:
+cd <yocto-workspace>/
+source oe-init-build-env [build-dir]
+
+Perhaps you have a fully setup Yocto workspace but are running this script from another directory;
+in this case, simply switch to your Yocto workspace and run it from there, f.e., like this:
+~/yocto_tools/${name} [...params...]"
+  exit 1
+}
+set -u
+
 echo "
 +++ NOTE Carefully Please +++
 Your current Yocto 'build' dir (\$BUILDDIR or \$TOPDIR) is
 \"${BUILDDIR}\"
 
-This implies that the layer/recipe dir tree and files will be created within
-this Yocto 'build' dir displayed above.
+This implies that the layer/recipe dir tree and files will be created like this:"
+if [[ ${OLDER_VER} -eq 1 ]] ; then
+   echo "(This is an older Yocto < 5.3): so, within this Yocto 'build' dir displayed above"
+else
+   echo "(This is a newer Yocto >= 5.3): so, within this project's layer location, here determined to be:
+ ${PRJ_LAYERS}"
+fi
+
+echo "
 If this is fine, press [Enter] to continue, else press ^C to abort"
 read -r
 
@@ -239,33 +263,40 @@ else
   LAYER=$1
   RCP_NAME=$2
 fi
-# Append a $PR = 0.1 to the recipe-name
+# strip out any '/' chars
+LAYER=$(echo "${LAYER}" | sed 's/\///g')
+RCP_NAME=$(echo "${RCP_NAME}" | sed 's/\///g')
 dprint "LAYER = ${LAYER}, RCP_NAME = ${RCP_NAME}"
+
+LAYER_DIR_PFX=${BUILDDIR}
+# New layer location: for 'new' Yocto >= 5.3: the project layers dir location
+# should be used, not just under the build-dir
+[[ ${OLDER_VER} -eq 1 ]] && {
+   set +u
+   [[ ! -z ${PRJ_LAYERS} ]] && LAYER_DIR_PFX=${PRJ_LAYERS}
+   set -u
+}
+
+export LAYER=${LAYER_DIR_PFX}/${LAYER}
+dprint "LAYER = ${LAYER}"
+# Append a $PR = 0.1 to the recipe-name
 
 # TODO : don't abort, proceed using existing layer for new recipe..
 LAYER_EXISTS=0
 [[ -d ${LAYER} ]] && LAYER_EXISTS=1 #&& die "Layer ${LAYER} already exists"
 
 #-- Validity checks
-layer_metatoken=$(echo "${LAYER}" |cut -d"-" -f1)
-[ "${layer_metatoken}" != "meta" ] && {
-  echo " Your meta-layername is \"${LAYER}\" ; convention dictates it should be of the form
- meta-<foo>"
-  exit 1 
-}
-export layer_token2=$(echo "${LAYER}" |cut -d"-" -f2)
-[ -z "${layer_token2}" ] && {
-  echo " Your meta-layername is \"${LAYER}\" ; convention dictates it should be of the form
- meta-<foo> (<foo> part is missing!)"
-  exit 1 
-}
-dprint "layer_token2 = ${layer_token2}"
+LAYERNAME="$(basename ${LAYER})"
+[[ "${LAYERNAME})" != *"-"* ]] && die "Your meta-layername is \"${LAYERNAME}\" ; convention dictates it should be of the form \"meta-<foo>\""
+layer_metatoken=$(echo "${LAYERNAME})" |cut -d"-" -f1)
+[ "${layer_metatoken}" != "meta" ] && die " Your meta-layername is \"${LAYERNAME}\"; convention dictates it should be of the form \"meta-<foo>\""
+export layer_token2=$(echo "${LAYERNAME}" |cut -d"-" -f2)
+#dprint "layer_token2 = ${layer_token2}"
+[ -z "${layer_token2}" ] && die " Your meta-layername is \"${LAYERNAME}\"; convention dictates it should be of the form
+ \"meta-<foo>\" (the <foo> part is missing!)"
 
 TOP=$(pwd)
 cd "${BUILDDIR}" || exit 1
-echo "Base Yocto workspace <pfx/build-dir> ::
-${BUILDDIR}
-"
 
 [[ ${LAYER_EXISTS} -eq 0 ]] && {
   bitbake-layers create-layer ${LAYER}
@@ -274,31 +305,31 @@ ${BUILDDIR}
 }
 
 # Setup the specified recipe dir and files
-RCP_FILES_DIR=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}
+#RCP_FILES_DIR=${BUILDDIR}/${LAYER}/recipes-${layer_token2}/${RCP_NAME}
+RCP_FILES_DIR=${LAYER}/recipes-${layer_token2}/${RCP_NAME}
 dprint "RCP_FILES_DIR = ${RCP_FILES_DIR}"
 [[ -d ${RCP_FILES_DIR} ]] && die "Layer:Recipe :: ${LAYER}:recipe-${layer_token2}/${RCP_NAME} already exists
 Either use another recipe name or create a new layer:recipe"
 
 #-- Create the basic tree
 RCP_FILES_DIR=${RCP_FILES_DIR}/files
-mkdir -p "${RCP_FILES_DIR}" || {
-  echo "Creating recipe dir \"${RCP_FILES_DIR}\" failed, aborting..."
-  exit 1
-}
+mkdir -p "${RCP_FILES_DIR}" || die "Creating recipe dir \"${RCP_FILES_DIR}\" failed, aborting..."
 
 # the 'bitbake-layers create-layer <...>' cmd itself sets up the conf/layer.conf file
 add_to_files_dir
 gen_recipe_file
-bitbake-layers add-layer ${LAYER}
+# Only add the layer if not there already
+bitbake-layers show-layers |grep "${LAYERNAME}" >/dev/null || bitbake-layers add-layer ${LAYER}
 
 echo
 [ ${WARN} -ne 0 ] && warn "
 *** ${name}: Note: some WARNings were generated ***
 "
-echo "Layer \"${LAYER}\" recipe \"${RCP_NAME}\" setup:
+echo "Layer \"$(basename ${LAYER})\" recipe \"${RCP_NAME}\" setup:
 "
 #tree "${BUILDDIR}"/"${LAYER}"/recipes-"${layer_token2}"
-tree "${BUILDDIR}"/"${LAYER}"/
+#tree "${BUILDDIR}"/"${LAYER}"/
+tree "${LAYER}"/
 
 cd "${TOP}"
 
@@ -309,6 +340,7 @@ echo " a) verify and update the recipe file(s)
     (typically via a IMAGE_INSTALL:append = \" ${RCP_NAME}\"
   TIP: doing a 'bitbake-layers show-recipes | grep -w -A2 xxx' one can check if recipe
   'xxx' is actually installed
- c) rebuild the project with 'bitbake <image-name>' and test
+ c) test the layer+recipe with 'bitbake <recipe-name>'
+ d) rebuild the project with 'bitbake <image-name>' and test
  "
 exit 0
